baseURL = 'https://negbg-web.pages.dev/'
languageCode = 'sv-SE'
title = 'Göteborgs största förening för fightingspel'
theme = 'hello-friend-ng'
#sectionPagesMenu = 'main'
pluralizeListTitles = false
relativeURLs = true
timeZone = "Europe/Stockholm"

[params.logo]
    path = "/NegativeEdge_Color_1024_1.png"
    alt = "NE-logga"
[params.header.logo]
    path = "/NegativeEdge_Color_1024_1.png"
    alt = "NE-logga"

[params]
  timeZoneAbbr = "CET/CEST"
  customCSS = ["/css/custom.css"]

  [[params.social]]
    name = "discord"
    url  = "https://discord.gg/kMVJ55wwy7"

  [[params.social]]
    name = "twitter"
    url  = "https://x.com/negativeedgegbg"

  [[params.social]]
    name = "facebook"
    url  = "https://www.facebook.com/share/1B3JfCMQGS/"

  [[params.social]]
    name = "twitch"
    url  = "https://www.twitch.tv/negativeedgegbg"




[[menu.main]]
  identifier = "events"
  name = "Evenemang"
  url = "/events/"
  weight = 10

[[menu.main]]
  identifier = "news"
  name = "Nyheter"
  url = "/nyheter/"
  weight = 20

[[menu.main]]
  identifier = "about"
  name = "Om oss"
  url = "/about/"
  weight = 30


  
[caches]
  [caches.images]
    dir = ':cacheDir'
