baseURL = 'https://negbg-web.pages.dev/'
languageCode = 'sv-SE'
title = 'Göteborgs största förening för fightingspel'
theme = 'hello-friend-ng'
#sectionPagesMenu = 'main'
pluralizeListTitles = false
relativeURLs = true
timeZone = "Europe/Stockholm"

[params]
  timeZoneAbbr = "CET/CEST"
  customCSS = ["/css/custom.css"]
  enableSharingButtons = true
[params.logo]
    path = "/NegativeEdge_Color_1024_1.png"
    alt = "NE-logga"
[params.header.logo]
    path = "/NegativeEdge_Color_1024_1.png"
    alt = "NE-logga"


[params.author]
    name = "Jane Doe"

[params.footer]
  trademark = "Negative Edge 2025"
  rss = true

  [[params.social]]
    name = "discord"
    url  = "https://discord.gg/kMVJ55wwy7"

  [[params.social]]
    name = "twitter"
    url  = "https://x.com/negativeedgegbg"

  [[params.social]]
    name = "facebook"
    url  = "https://www.facebook.com/share/1B3JfCMQGS/"

  [[params.social]]
    name = "twitch"
    url  = "https://www.twitch.tv/negativeedgegbg"

  
[caches]
  [caches.images]
    dir = ':cacheDir'
