
[recurrence]
  start_time = "18:00"
  end_time = "22:00"
  
  schedule = [
    "2025-11-04", # Tis
    "2025-11-12", # Ons
    "2025-11-18", # Tis
    "2025-11-26", # Ons
    "2025-12-02", # Tis
    "2025-12-10", # Ons
  ]
  
  cancellations = [
    "2025-11-04",
    "2025-11-12",
    "2025-11-18", # Tis
  ]
